/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the SalesRuleDataRuleLabelInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SalesRuleDataRuleLabelInterface{}

// SalesRuleDataRuleLabelInterface Interface RuleLabelInterface
type SalesRuleDataRuleLabelInterface struct {
	// StoreId
	StoreId int32 `json:"store_id"`
	// The label for the store
	StoreLabel string `json:"store_label"`
	// ExtensionInterface class for @see \\Magento\\SalesRule\\Api\\Data\\RuleLabelInterface
	ExtensionAttributes  map[string]interface{} `json:"extension_attributes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SalesRuleDataRuleLabelInterface SalesRuleDataRuleLabelInterface

// NewSalesRuleDataRuleLabelInterface instantiates a new SalesRuleDataRuleLabelInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSalesRuleDataRuleLabelInterface(storeId int32, storeLabel string) *SalesRuleDataRuleLabelInterface {
	this := SalesRuleDataRuleLabelInterface{}
	this.StoreId = storeId
	this.StoreLabel = storeLabel
	return &this
}

// NewSalesRuleDataRuleLabelInterfaceWithDefaults instantiates a new SalesRuleDataRuleLabelInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSalesRuleDataRuleLabelInterfaceWithDefaults() *SalesRuleDataRuleLabelInterface {
	this := SalesRuleDataRuleLabelInterface{}
	return &this
}

// GetStoreId returns the StoreId field value
func (o *SalesRuleDataRuleLabelInterface) GetStoreId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StoreId
}

// GetStoreIdOk returns a tuple with the StoreId field value
// and a boolean to check if the value has been set.
func (o *SalesRuleDataRuleLabelInterface) GetStoreIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoreId, true
}

// SetStoreId sets field value
func (o *SalesRuleDataRuleLabelInterface) SetStoreId(v int32) {
	o.StoreId = v
}

// GetStoreLabel returns the StoreLabel field value
func (o *SalesRuleDataRuleLabelInterface) GetStoreLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StoreLabel
}

// GetStoreLabelOk returns a tuple with the StoreLabel field value
// and a boolean to check if the value has been set.
func (o *SalesRuleDataRuleLabelInterface) GetStoreLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoreLabel, true
}

// SetStoreLabel sets field value
func (o *SalesRuleDataRuleLabelInterface) SetStoreLabel(v string) {
	o.StoreLabel = v
}

// GetExtensionAttributes returns the ExtensionAttributes field value if set, zero value otherwise.
func (o *SalesRuleDataRuleLabelInterface) GetExtensionAttributes() map[string]interface{} {
	if o == nil || IsNil(o.ExtensionAttributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.ExtensionAttributes
}

// GetExtensionAttributesOk returns a tuple with the ExtensionAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesRuleDataRuleLabelInterface) GetExtensionAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExtensionAttributes) {
		return map[string]interface{}{}, false
	}
	return o.ExtensionAttributes, true
}

// HasExtensionAttributes returns a boolean if a field has been set.
func (o *SalesRuleDataRuleLabelInterface) HasExtensionAttributes() bool {
	if o != nil && !IsNil(o.ExtensionAttributes) {
		return true
	}

	return false
}

// SetExtensionAttributes gets a reference to the given map[string]interface{} and assigns it to the ExtensionAttributes field.
func (o *SalesRuleDataRuleLabelInterface) SetExtensionAttributes(v map[string]interface{}) {
	o.ExtensionAttributes = v
}

func (o SalesRuleDataRuleLabelInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SalesRuleDataRuleLabelInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["store_id"] = o.StoreId
	toSerialize["store_label"] = o.StoreLabel
	if !IsNil(o.ExtensionAttributes) {
		toSerialize["extension_attributes"] = o.ExtensionAttributes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SalesRuleDataRuleLabelInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"store_id",
		"store_label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSalesRuleDataRuleLabelInterface := _SalesRuleDataRuleLabelInterface{}

	err = json.Unmarshal(data, &varSalesRuleDataRuleLabelInterface)

	if err != nil {
		return err
	}

	*o = SalesRuleDataRuleLabelInterface(varSalesRuleDataRuleLabelInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "store_id")
		delete(additionalProperties, "store_label")
		delete(additionalProperties, "extension_attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *SalesRuleDataRuleLabelInterface) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *SalesRuleDataRuleLabelInterface) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableSalesRuleDataRuleLabelInterface struct {
	value *SalesRuleDataRuleLabelInterface
	isSet bool
}

func (v NullableSalesRuleDataRuleLabelInterface) Get() *SalesRuleDataRuleLabelInterface {
	return v.value
}

func (v *NullableSalesRuleDataRuleLabelInterface) Set(val *SalesRuleDataRuleLabelInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableSalesRuleDataRuleLabelInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableSalesRuleDataRuleLabelInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSalesRuleDataRuleLabelInterface(val *SalesRuleDataRuleLabelInterface) *NullableSalesRuleDataRuleLabelInterface {
	return &NullableSalesRuleDataRuleLabelInterface{value: val, isSet: true}
}

func (v NullableSalesRuleDataRuleLabelInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSalesRuleDataRuleLabelInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
