/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the PostV1NegotiableQuoteSubmitToCustomerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV1NegotiableQuoteSubmitToCustomerRequest{}

// PostV1NegotiableQuoteSubmitToCustomerRequest struct for PostV1NegotiableQuoteSubmitToCustomerRequest
type PostV1NegotiableQuoteSubmitToCustomerRequest struct {
	QuoteId              int32                                           `json:"quoteId"`
	Comment              *string                                         `json:"comment,omitempty"`
	Files                []NegotiableQuoteDataAttachmentContentInterface `json:"files,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PostV1NegotiableQuoteSubmitToCustomerRequest PostV1NegotiableQuoteSubmitToCustomerRequest

// NewPostV1NegotiableQuoteSubmitToCustomerRequest instantiates a new PostV1NegotiableQuoteSubmitToCustomerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV1NegotiableQuoteSubmitToCustomerRequest(quoteId int32) *PostV1NegotiableQuoteSubmitToCustomerRequest {
	this := PostV1NegotiableQuoteSubmitToCustomerRequest{}
	this.QuoteId = quoteId
	return &this
}

// NewPostV1NegotiableQuoteSubmitToCustomerRequestWithDefaults instantiates a new PostV1NegotiableQuoteSubmitToCustomerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV1NegotiableQuoteSubmitToCustomerRequestWithDefaults() *PostV1NegotiableQuoteSubmitToCustomerRequest {
	this := PostV1NegotiableQuoteSubmitToCustomerRequest{}
	return &this
}

// GetQuoteId returns the QuoteId field value
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) GetQuoteId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.QuoteId
}

// GetQuoteIdOk returns a tuple with the QuoteId field value
// and a boolean to check if the value has been set.
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) GetQuoteIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteId, true
}

// SetQuoteId sets field value
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) SetQuoteId(v int32) {
	o.QuoteId = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) SetComment(v string) {
	o.Comment = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) GetFiles() []NegotiableQuoteDataAttachmentContentInterface {
	if o == nil || IsNil(o.Files) {
		var ret []NegotiableQuoteDataAttachmentContentInterface
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) GetFilesOk() ([]NegotiableQuoteDataAttachmentContentInterface, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []NegotiableQuoteDataAttachmentContentInterface and assigns it to the Files field.
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) SetFiles(v []NegotiableQuoteDataAttachmentContentInterface) {
	o.Files = v
}

func (o PostV1NegotiableQuoteSubmitToCustomerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV1NegotiableQuoteSubmitToCustomerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quoteId"] = o.QuoteId
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quoteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostV1NegotiableQuoteSubmitToCustomerRequest := _PostV1NegotiableQuoteSubmitToCustomerRequest{}

	err = json.Unmarshal(data, &varPostV1NegotiableQuoteSubmitToCustomerRequest)

	if err != nil {
		return err
	}

	*o = PostV1NegotiableQuoteSubmitToCustomerRequest(varPostV1NegotiableQuoteSubmitToCustomerRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "quoteId")
		delete(additionalProperties, "comment")
		delete(additionalProperties, "files")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *PostV1NegotiableQuoteSubmitToCustomerRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullablePostV1NegotiableQuoteSubmitToCustomerRequest struct {
	value *PostV1NegotiableQuoteSubmitToCustomerRequest
	isSet bool
}

func (v NullablePostV1NegotiableQuoteSubmitToCustomerRequest) Get() *PostV1NegotiableQuoteSubmitToCustomerRequest {
	return v.value
}

func (v *NullablePostV1NegotiableQuoteSubmitToCustomerRequest) Set(val *PostV1NegotiableQuoteSubmitToCustomerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV1NegotiableQuoteSubmitToCustomerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV1NegotiableQuoteSubmitToCustomerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV1NegotiableQuoteSubmitToCustomerRequest(val *PostV1NegotiableQuoteSubmitToCustomerRequest) *NullablePostV1NegotiableQuoteSubmitToCustomerRequest {
	return &NullablePostV1NegotiableQuoteSubmitToCustomerRequest{value: val, isSet: true}
}

func (v NullablePostV1NegotiableQuoteSubmitToCustomerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV1NegotiableQuoteSubmitToCustomerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
