/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the PutV1CartsCartIdRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutV1CartsCartIdRequest{}

// PutV1CartsCartIdRequest struct for PutV1CartsCartIdRequest
type PutV1CartsCartIdRequest struct {
	// The customer ID.
	CustomerId           int32 `json:"customerId"`
	StoreId              int32 `json:"storeId"`
	AdditionalProperties map[string]interface{}
}

type _PutV1CartsCartIdRequest PutV1CartsCartIdRequest

// NewPutV1CartsCartIdRequest instantiates a new PutV1CartsCartIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutV1CartsCartIdRequest(customerId int32, storeId int32) *PutV1CartsCartIdRequest {
	this := PutV1CartsCartIdRequest{}
	this.CustomerId = customerId
	this.StoreId = storeId
	return &this
}

// NewPutV1CartsCartIdRequestWithDefaults instantiates a new PutV1CartsCartIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutV1CartsCartIdRequestWithDefaults() *PutV1CartsCartIdRequest {
	this := PutV1CartsCartIdRequest{}
	return &this
}

// GetCustomerId returns the CustomerId field value
func (o *PutV1CartsCartIdRequest) GetCustomerId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *PutV1CartsCartIdRequest) GetCustomerIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *PutV1CartsCartIdRequest) SetCustomerId(v int32) {
	o.CustomerId = v
}

// GetStoreId returns the StoreId field value
func (o *PutV1CartsCartIdRequest) GetStoreId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StoreId
}

// GetStoreIdOk returns a tuple with the StoreId field value
// and a boolean to check if the value has been set.
func (o *PutV1CartsCartIdRequest) GetStoreIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoreId, true
}

// SetStoreId sets field value
func (o *PutV1CartsCartIdRequest) SetStoreId(v int32) {
	o.StoreId = v
}

func (o PutV1CartsCartIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutV1CartsCartIdRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customerId"] = o.CustomerId
	toSerialize["storeId"] = o.StoreId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PutV1CartsCartIdRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customerId",
		"storeId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPutV1CartsCartIdRequest := _PutV1CartsCartIdRequest{}

	err = json.Unmarshal(data, &varPutV1CartsCartIdRequest)

	if err != nil {
		return err
	}

	*o = PutV1CartsCartIdRequest(varPutV1CartsCartIdRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customerId")
		delete(additionalProperties, "storeId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PutV1CartsCartIdRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *PutV1CartsCartIdRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullablePutV1CartsCartIdRequest struct {
	value *PutV1CartsCartIdRequest
	isSet bool
}

func (v NullablePutV1CartsCartIdRequest) Get() *PutV1CartsCartIdRequest {
	return v.value
}

func (v *NullablePutV1CartsCartIdRequest) Set(val *PutV1CartsCartIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutV1CartsCartIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutV1CartsCartIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutV1CartsCartIdRequest(val *PutV1CartsCartIdRequest) *NullablePutV1CartsCartIdRequest {
	return &NullablePutV1CartsCartIdRequest{value: val, isSet: true}
}

func (v NullablePutV1CartsCartIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutV1CartsCartIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
