/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the DirectoryDataRegionInformationInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectoryDataRegionInformationInterface{}

// DirectoryDataRegionInformationInterface Region Information interface.
type DirectoryDataRegionInformationInterface struct {
	// Region id
	Id string `json:"id"`
	// Region code
	Code string `json:"code"`
	// Region name
	Name string `json:"name"`
	// ExtensionInterface class for @see \\Magento\\Directory\\Api\\Data\\RegionInformationInterface
	ExtensionAttributes  map[string]interface{} `json:"extension_attributes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DirectoryDataRegionInformationInterface DirectoryDataRegionInformationInterface

// NewDirectoryDataRegionInformationInterface instantiates a new DirectoryDataRegionInformationInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectoryDataRegionInformationInterface(id string, code string, name string) *DirectoryDataRegionInformationInterface {
	this := DirectoryDataRegionInformationInterface{}
	this.Id = id
	this.Code = code
	this.Name = name
	return &this
}

// NewDirectoryDataRegionInformationInterfaceWithDefaults instantiates a new DirectoryDataRegionInformationInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryDataRegionInformationInterfaceWithDefaults() *DirectoryDataRegionInformationInterface {
	this := DirectoryDataRegionInformationInterface{}
	return &this
}

// GetId returns the Id field value
func (o *DirectoryDataRegionInformationInterface) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DirectoryDataRegionInformationInterface) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DirectoryDataRegionInformationInterface) SetId(v string) {
	o.Id = v
}

// GetCode returns the Code field value
func (o *DirectoryDataRegionInformationInterface) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *DirectoryDataRegionInformationInterface) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *DirectoryDataRegionInformationInterface) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *DirectoryDataRegionInformationInterface) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DirectoryDataRegionInformationInterface) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DirectoryDataRegionInformationInterface) SetName(v string) {
	o.Name = v
}

// GetExtensionAttributes returns the ExtensionAttributes field value if set, zero value otherwise.
func (o *DirectoryDataRegionInformationInterface) GetExtensionAttributes() map[string]interface{} {
	if o == nil || IsNil(o.ExtensionAttributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.ExtensionAttributes
}

// GetExtensionAttributesOk returns a tuple with the ExtensionAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryDataRegionInformationInterface) GetExtensionAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExtensionAttributes) {
		return map[string]interface{}{}, false
	}
	return o.ExtensionAttributes, true
}

// HasExtensionAttributes returns a boolean if a field has been set.
func (o *DirectoryDataRegionInformationInterface) HasExtensionAttributes() bool {
	if o != nil && !IsNil(o.ExtensionAttributes) {
		return true
	}

	return false
}

// SetExtensionAttributes gets a reference to the given map[string]interface{} and assigns it to the ExtensionAttributes field.
func (o *DirectoryDataRegionInformationInterface) SetExtensionAttributes(v map[string]interface{}) {
	o.ExtensionAttributes = v
}

func (o DirectoryDataRegionInformationInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectoryDataRegionInformationInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	if !IsNil(o.ExtensionAttributes) {
		toSerialize["extension_attributes"] = o.ExtensionAttributes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DirectoryDataRegionInformationInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"code",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectoryDataRegionInformationInterface := _DirectoryDataRegionInformationInterface{}

	err = json.Unmarshal(data, &varDirectoryDataRegionInformationInterface)

	if err != nil {
		return err
	}

	*o = DirectoryDataRegionInformationInterface(varDirectoryDataRegionInformationInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "code")
		delete(additionalProperties, "name")
		delete(additionalProperties, "extension_attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *DirectoryDataRegionInformationInterface) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *DirectoryDataRegionInformationInterface) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableDirectoryDataRegionInformationInterface struct {
	value *DirectoryDataRegionInformationInterface
	isSet bool
}

func (v NullableDirectoryDataRegionInformationInterface) Get() *DirectoryDataRegionInformationInterface {
	return v.value
}

func (v *NullableDirectoryDataRegionInformationInterface) Set(val *DirectoryDataRegionInformationInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectoryDataRegionInformationInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectoryDataRegionInformationInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectoryDataRegionInformationInterface(val *DirectoryDataRegionInformationInterface) *NullableDirectoryDataRegionInformationInterface {
	return &NullableDirectoryDataRegionInformationInterface{value: val, isSet: true}
}

func (v NullableDirectoryDataRegionInformationInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectoryDataRegionInformationInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
