/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the EavDataAttributeValidationRuleInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EavDataAttributeValidationRuleInterface{}

// EavDataAttributeValidationRuleInterface Interface AttributeValidationRuleInterface
type EavDataAttributeValidationRuleInterface struct {
	// Object key
	Key string `json:"key"`
	// Object value
	Value                string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _EavDataAttributeValidationRuleInterface EavDataAttributeValidationRuleInterface

// NewEavDataAttributeValidationRuleInterface instantiates a new EavDataAttributeValidationRuleInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEavDataAttributeValidationRuleInterface(key string, value string) *EavDataAttributeValidationRuleInterface {
	this := EavDataAttributeValidationRuleInterface{}
	this.Key = key
	this.Value = value
	return &this
}

// NewEavDataAttributeValidationRuleInterfaceWithDefaults instantiates a new EavDataAttributeValidationRuleInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEavDataAttributeValidationRuleInterfaceWithDefaults() *EavDataAttributeValidationRuleInterface {
	this := EavDataAttributeValidationRuleInterface{}
	return &this
}

// GetKey returns the Key field value
func (o *EavDataAttributeValidationRuleInterface) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *EavDataAttributeValidationRuleInterface) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *EavDataAttributeValidationRuleInterface) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *EavDataAttributeValidationRuleInterface) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *EavDataAttributeValidationRuleInterface) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *EavDataAttributeValidationRuleInterface) SetValue(v string) {
	o.Value = v
}

func (o EavDataAttributeValidationRuleInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EavDataAttributeValidationRuleInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EavDataAttributeValidationRuleInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEavDataAttributeValidationRuleInterface := _EavDataAttributeValidationRuleInterface{}

	err = json.Unmarshal(data, &varEavDataAttributeValidationRuleInterface)

	if err != nil {
		return err
	}

	*o = EavDataAttributeValidationRuleInterface(varEavDataAttributeValidationRuleInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *EavDataAttributeValidationRuleInterface) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *EavDataAttributeValidationRuleInterface) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableEavDataAttributeValidationRuleInterface struct {
	value *EavDataAttributeValidationRuleInterface
	isSet bool
}

func (v NullableEavDataAttributeValidationRuleInterface) Get() *EavDataAttributeValidationRuleInterface {
	return v.value
}

func (v *NullableEavDataAttributeValidationRuleInterface) Set(val *EavDataAttributeValidationRuleInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableEavDataAttributeValidationRuleInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableEavDataAttributeValidationRuleInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEavDataAttributeValidationRuleInterface(val *EavDataAttributeValidationRuleInterface) *NullableEavDataAttributeValidationRuleInterface {
	return &NullableEavDataAttributeValidationRuleInterface{value: val, isSet: true}
}

func (v NullableEavDataAttributeValidationRuleInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEavDataAttributeValidationRuleInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
