/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the PostV1CmsPageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV1CmsPageRequest{}

// PostV1CmsPageRequest struct for PostV1CmsPageRequest
type PostV1CmsPageRequest struct {
	Page                 CmsDataPageInterface `json:"page"`
	AdditionalProperties map[string]interface{}
}

type _PostV1CmsPageRequest PostV1CmsPageRequest

// NewPostV1CmsPageRequest instantiates a new PostV1CmsPageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV1CmsPageRequest(page CmsDataPageInterface) *PostV1CmsPageRequest {
	this := PostV1CmsPageRequest{}
	this.Page = page
	return &this
}

// NewPostV1CmsPageRequestWithDefaults instantiates a new PostV1CmsPageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV1CmsPageRequestWithDefaults() *PostV1CmsPageRequest {
	this := PostV1CmsPageRequest{}
	return &this
}

// GetPage returns the Page field value
func (o *PostV1CmsPageRequest) GetPage() CmsDataPageInterface {
	if o == nil {
		var ret CmsDataPageInterface
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *PostV1CmsPageRequest) GetPageOk() (*CmsDataPageInterface, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *PostV1CmsPageRequest) SetPage(v CmsDataPageInterface) {
	o.Page = v
}

func (o PostV1CmsPageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV1CmsPageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostV1CmsPageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostV1CmsPageRequest := _PostV1CmsPageRequest{}

	err = json.Unmarshal(data, &varPostV1CmsPageRequest)

	if err != nil {
		return err
	}

	*o = PostV1CmsPageRequest(varPostV1CmsPageRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "page")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PostV1CmsPageRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *PostV1CmsPageRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullablePostV1CmsPageRequest struct {
	value *PostV1CmsPageRequest
	isSet bool
}

func (v NullablePostV1CmsPageRequest) Get() *PostV1CmsPageRequest {
	return v.value
}

func (v *NullablePostV1CmsPageRequest) Set(val *PostV1CmsPageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV1CmsPageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV1CmsPageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV1CmsPageRequest(val *PostV1CmsPageRequest) *NullablePostV1CmsPageRequest {
	return &NullablePostV1CmsPageRequest{value: val, isSet: true}
}

func (v NullablePostV1CmsPageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV1CmsPageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
