/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the PostV1InventorySourceselectionalgorithmresultRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV1InventorySourceselectionalgorithmresultRequest{}

// PostV1InventorySourceselectionalgorithmresultRequest struct for PostV1InventorySourceselectionalgorithmresultRequest
type PostV1InventorySourceselectionalgorithmresultRequest struct {
	InventoryRequest     InventorySourceSelectionApiDataInventoryRequestInterface `json:"inventoryRequest"`
	AlgorithmCode        string                                                   `json:"algorithmCode"`
	AdditionalProperties map[string]interface{}
}

type _PostV1InventorySourceselectionalgorithmresultRequest PostV1InventorySourceselectionalgorithmresultRequest

// NewPostV1InventorySourceselectionalgorithmresultRequest instantiates a new PostV1InventorySourceselectionalgorithmresultRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV1InventorySourceselectionalgorithmresultRequest(inventoryRequest InventorySourceSelectionApiDataInventoryRequestInterface, algorithmCode string) *PostV1InventorySourceselectionalgorithmresultRequest {
	this := PostV1InventorySourceselectionalgorithmresultRequest{}
	this.InventoryRequest = inventoryRequest
	this.AlgorithmCode = algorithmCode
	return &this
}

// NewPostV1InventorySourceselectionalgorithmresultRequestWithDefaults instantiates a new PostV1InventorySourceselectionalgorithmresultRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV1InventorySourceselectionalgorithmresultRequestWithDefaults() *PostV1InventorySourceselectionalgorithmresultRequest {
	this := PostV1InventorySourceselectionalgorithmresultRequest{}
	return &this
}

// GetInventoryRequest returns the InventoryRequest field value
func (o *PostV1InventorySourceselectionalgorithmresultRequest) GetInventoryRequest() InventorySourceSelectionApiDataInventoryRequestInterface {
	if o == nil {
		var ret InventorySourceSelectionApiDataInventoryRequestInterface
		return ret
	}

	return o.InventoryRequest
}

// GetInventoryRequestOk returns a tuple with the InventoryRequest field value
// and a boolean to check if the value has been set.
func (o *PostV1InventorySourceselectionalgorithmresultRequest) GetInventoryRequestOk() (*InventorySourceSelectionApiDataInventoryRequestInterface, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InventoryRequest, true
}

// SetInventoryRequest sets field value
func (o *PostV1InventorySourceselectionalgorithmresultRequest) SetInventoryRequest(v InventorySourceSelectionApiDataInventoryRequestInterface) {
	o.InventoryRequest = v
}

// GetAlgorithmCode returns the AlgorithmCode field value
func (o *PostV1InventorySourceselectionalgorithmresultRequest) GetAlgorithmCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AlgorithmCode
}

// GetAlgorithmCodeOk returns a tuple with the AlgorithmCode field value
// and a boolean to check if the value has been set.
func (o *PostV1InventorySourceselectionalgorithmresultRequest) GetAlgorithmCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlgorithmCode, true
}

// SetAlgorithmCode sets field value
func (o *PostV1InventorySourceselectionalgorithmresultRequest) SetAlgorithmCode(v string) {
	o.AlgorithmCode = v
}

func (o PostV1InventorySourceselectionalgorithmresultRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV1InventorySourceselectionalgorithmresultRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["inventoryRequest"] = o.InventoryRequest
	toSerialize["algorithmCode"] = o.AlgorithmCode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostV1InventorySourceselectionalgorithmresultRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inventoryRequest",
		"algorithmCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostV1InventorySourceselectionalgorithmresultRequest := _PostV1InventorySourceselectionalgorithmresultRequest{}

	err = json.Unmarshal(data, &varPostV1InventorySourceselectionalgorithmresultRequest)

	if err != nil {
		return err
	}

	*o = PostV1InventorySourceselectionalgorithmresultRequest(varPostV1InventorySourceselectionalgorithmresultRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "inventoryRequest")
		delete(additionalProperties, "algorithmCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PostV1InventorySourceselectionalgorithmresultRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *PostV1InventorySourceselectionalgorithmresultRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullablePostV1InventorySourceselectionalgorithmresultRequest struct {
	value *PostV1InventorySourceselectionalgorithmresultRequest
	isSet bool
}

func (v NullablePostV1InventorySourceselectionalgorithmresultRequest) Get() *PostV1InventorySourceselectionalgorithmresultRequest {
	return v.value
}

func (v *NullablePostV1InventorySourceselectionalgorithmresultRequest) Set(val *PostV1InventorySourceselectionalgorithmresultRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV1InventorySourceselectionalgorithmresultRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV1InventorySourceselectionalgorithmresultRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV1InventorySourceselectionalgorithmresultRequest(val *PostV1InventorySourceselectionalgorithmresultRequest) *NullablePostV1InventorySourceselectionalgorithmresultRequest {
	return &NullablePostV1InventorySourceselectionalgorithmresultRequest{value: val, isSet: true}
}

func (v NullablePostV1InventorySourceselectionalgorithmresultRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV1InventorySourceselectionalgorithmresultRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
