/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
)

// checks if the CatalogDataProductLinkExtensionInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogDataProductLinkExtensionInterface{}

// CatalogDataProductLinkExtensionInterface ExtensionInterface class for @see \\Magento\\Catalog\\Api\\Data\\ProductLinkInterface
type CatalogDataProductLinkExtensionInterface struct {
	Qty                  *float32 `json:"qty,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CatalogDataProductLinkExtensionInterface CatalogDataProductLinkExtensionInterface

// NewCatalogDataProductLinkExtensionInterface instantiates a new CatalogDataProductLinkExtensionInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogDataProductLinkExtensionInterface() *CatalogDataProductLinkExtensionInterface {
	this := CatalogDataProductLinkExtensionInterface{}
	return &this
}

// NewCatalogDataProductLinkExtensionInterfaceWithDefaults instantiates a new CatalogDataProductLinkExtensionInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogDataProductLinkExtensionInterfaceWithDefaults() *CatalogDataProductLinkExtensionInterface {
	this := CatalogDataProductLinkExtensionInterface{}
	return &this
}

// GetQty returns the Qty field value if set, zero value otherwise.
func (o *CatalogDataProductLinkExtensionInterface) GetQty() float32 {
	if o == nil || IsNil(o.Qty) {
		var ret float32
		return ret
	}
	return *o.Qty
}

// GetQtyOk returns a tuple with the Qty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogDataProductLinkExtensionInterface) GetQtyOk() (*float32, bool) {
	if o == nil || IsNil(o.Qty) {
		return nil, false
	}
	return o.Qty, true
}

// HasQty returns a boolean if a field has been set.
func (o *CatalogDataProductLinkExtensionInterface) HasQty() bool {
	if o != nil && !IsNil(o.Qty) {
		return true
	}

	return false
}

// SetQty gets a reference to the given float32 and assigns it to the Qty field.
func (o *CatalogDataProductLinkExtensionInterface) SetQty(v float32) {
	o.Qty = &v
}

func (o CatalogDataProductLinkExtensionInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogDataProductLinkExtensionInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Qty) {
		toSerialize["qty"] = o.Qty
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CatalogDataProductLinkExtensionInterface) UnmarshalJSON(data []byte) (err error) {
	varCatalogDataProductLinkExtensionInterface := _CatalogDataProductLinkExtensionInterface{}

	err = json.Unmarshal(data, &varCatalogDataProductLinkExtensionInterface)

	if err != nil {
		return err
	}

	*o = CatalogDataProductLinkExtensionInterface(varCatalogDataProductLinkExtensionInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "qty")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *CatalogDataProductLinkExtensionInterface) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *CatalogDataProductLinkExtensionInterface) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableCatalogDataProductLinkExtensionInterface struct {
	value *CatalogDataProductLinkExtensionInterface
	isSet bool
}

func (v NullableCatalogDataProductLinkExtensionInterface) Get() *CatalogDataProductLinkExtensionInterface {
	return v.value
}

func (v *NullableCatalogDataProductLinkExtensionInterface) Set(val *CatalogDataProductLinkExtensionInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogDataProductLinkExtensionInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogDataProductLinkExtensionInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogDataProductLinkExtensionInterface(val *CatalogDataProductLinkExtensionInterface) *NullableCatalogDataProductLinkExtensionInterface {
	return &NullableCatalogDataProductLinkExtensionInterface{value: val, isSet: true}
}

func (v NullableCatalogDataProductLinkExtensionInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogDataProductLinkExtensionInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
