/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the PostV1TfaProviderAuthyAuthenticateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV1TfaProviderAuthyAuthenticateRequest{}

// PostV1TfaProviderAuthyAuthenticateRequest struct for PostV1TfaProviderAuthyAuthenticateRequest
type PostV1TfaProviderAuthyAuthenticateRequest struct {
	Username             string `json:"username"`
	Password             string `json:"password"`
	Otp                  string `json:"otp"`
	AdditionalProperties map[string]interface{}
}

type _PostV1TfaProviderAuthyAuthenticateRequest PostV1TfaProviderAuthyAuthenticateRequest

// NewPostV1TfaProviderAuthyAuthenticateRequest instantiates a new PostV1TfaProviderAuthyAuthenticateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV1TfaProviderAuthyAuthenticateRequest(username string, password string, otp string) *PostV1TfaProviderAuthyAuthenticateRequest {
	this := PostV1TfaProviderAuthyAuthenticateRequest{}
	this.Username = username
	this.Password = password
	this.Otp = otp
	return &this
}

// NewPostV1TfaProviderAuthyAuthenticateRequestWithDefaults instantiates a new PostV1TfaProviderAuthyAuthenticateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV1TfaProviderAuthyAuthenticateRequestWithDefaults() *PostV1TfaProviderAuthyAuthenticateRequest {
	this := PostV1TfaProviderAuthyAuthenticateRequest{}
	return &this
}

// GetUsername returns the Username field value
func (o *PostV1TfaProviderAuthyAuthenticateRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *PostV1TfaProviderAuthyAuthenticateRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *PostV1TfaProviderAuthyAuthenticateRequest) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *PostV1TfaProviderAuthyAuthenticateRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *PostV1TfaProviderAuthyAuthenticateRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *PostV1TfaProviderAuthyAuthenticateRequest) SetPassword(v string) {
	o.Password = v
}

// GetOtp returns the Otp field value
func (o *PostV1TfaProviderAuthyAuthenticateRequest) GetOtp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Otp
}

// GetOtpOk returns a tuple with the Otp field value
// and a boolean to check if the value has been set.
func (o *PostV1TfaProviderAuthyAuthenticateRequest) GetOtpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Otp, true
}

// SetOtp sets field value
func (o *PostV1TfaProviderAuthyAuthenticateRequest) SetOtp(v string) {
	o.Otp = v
}

func (o PostV1TfaProviderAuthyAuthenticateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV1TfaProviderAuthyAuthenticateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	toSerialize["otp"] = o.Otp

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostV1TfaProviderAuthyAuthenticateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"password",
		"otp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostV1TfaProviderAuthyAuthenticateRequest := _PostV1TfaProviderAuthyAuthenticateRequest{}

	err = json.Unmarshal(data, &varPostV1TfaProviderAuthyAuthenticateRequest)

	if err != nil {
		return err
	}

	*o = PostV1TfaProviderAuthyAuthenticateRequest(varPostV1TfaProviderAuthyAuthenticateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		delete(additionalProperties, "otp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PostV1TfaProviderAuthyAuthenticateRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *PostV1TfaProviderAuthyAuthenticateRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullablePostV1TfaProviderAuthyAuthenticateRequest struct {
	value *PostV1TfaProviderAuthyAuthenticateRequest
	isSet bool
}

func (v NullablePostV1TfaProviderAuthyAuthenticateRequest) Get() *PostV1TfaProviderAuthyAuthenticateRequest {
	return v.value
}

func (v *NullablePostV1TfaProviderAuthyAuthenticateRequest) Set(val *PostV1TfaProviderAuthyAuthenticateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV1TfaProviderAuthyAuthenticateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV1TfaProviderAuthyAuthenticateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV1TfaProviderAuthyAuthenticateRequest(val *PostV1TfaProviderAuthyAuthenticateRequest) *NullablePostV1TfaProviderAuthyAuthenticateRequest {
	return &NullablePostV1TfaProviderAuthyAuthenticateRequest{value: val, isSet: true}
}

func (v NullablePostV1TfaProviderAuthyAuthenticateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV1TfaProviderAuthyAuthenticateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
