/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the AdobeCommerceEventsClientDataEventFieldInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdobeCommerceEventsClientDataEventFieldInterface{}

// AdobeCommerceEventsClientDataEventFieldInterface Interface for event field data from webapi requests
type AdobeCommerceEventsClientDataEventFieldInterface struct {
	// Event field name
	Name string `json:"name"`
	// Event field converter
	Converter            string `json:"converter"`
	AdditionalProperties map[string]interface{}
}

type _AdobeCommerceEventsClientDataEventFieldInterface AdobeCommerceEventsClientDataEventFieldInterface

// NewAdobeCommerceEventsClientDataEventFieldInterface instantiates a new AdobeCommerceEventsClientDataEventFieldInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdobeCommerceEventsClientDataEventFieldInterface(name string, converter string) *AdobeCommerceEventsClientDataEventFieldInterface {
	this := AdobeCommerceEventsClientDataEventFieldInterface{}
	this.Name = name
	this.Converter = converter
	return &this
}

// NewAdobeCommerceEventsClientDataEventFieldInterfaceWithDefaults instantiates a new AdobeCommerceEventsClientDataEventFieldInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdobeCommerceEventsClientDataEventFieldInterfaceWithDefaults() *AdobeCommerceEventsClientDataEventFieldInterface {
	this := AdobeCommerceEventsClientDataEventFieldInterface{}
	return &this
}

// GetName returns the Name field value
func (o *AdobeCommerceEventsClientDataEventFieldInterface) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AdobeCommerceEventsClientDataEventFieldInterface) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AdobeCommerceEventsClientDataEventFieldInterface) SetName(v string) {
	o.Name = v
}

// GetConverter returns the Converter field value
func (o *AdobeCommerceEventsClientDataEventFieldInterface) GetConverter() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Converter
}

// GetConverterOk returns a tuple with the Converter field value
// and a boolean to check if the value has been set.
func (o *AdobeCommerceEventsClientDataEventFieldInterface) GetConverterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Converter, true
}

// SetConverter sets field value
func (o *AdobeCommerceEventsClientDataEventFieldInterface) SetConverter(v string) {
	o.Converter = v
}

func (o AdobeCommerceEventsClientDataEventFieldInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdobeCommerceEventsClientDataEventFieldInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["converter"] = o.Converter

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdobeCommerceEventsClientDataEventFieldInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"converter",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdobeCommerceEventsClientDataEventFieldInterface := _AdobeCommerceEventsClientDataEventFieldInterface{}

	err = json.Unmarshal(data, &varAdobeCommerceEventsClientDataEventFieldInterface)

	if err != nil {
		return err
	}

	*o = AdobeCommerceEventsClientDataEventFieldInterface(varAdobeCommerceEventsClientDataEventFieldInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "converter")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *AdobeCommerceEventsClientDataEventFieldInterface) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *AdobeCommerceEventsClientDataEventFieldInterface) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableAdobeCommerceEventsClientDataEventFieldInterface struct {
	value *AdobeCommerceEventsClientDataEventFieldInterface
	isSet bool
}

func (v NullableAdobeCommerceEventsClientDataEventFieldInterface) Get() *AdobeCommerceEventsClientDataEventFieldInterface {
	return v.value
}

func (v *NullableAdobeCommerceEventsClientDataEventFieldInterface) Set(val *AdobeCommerceEventsClientDataEventFieldInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableAdobeCommerceEventsClientDataEventFieldInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableAdobeCommerceEventsClientDataEventFieldInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdobeCommerceEventsClientDataEventFieldInterface(val *AdobeCommerceEventsClientDataEventFieldInterface) *NullableAdobeCommerceEventsClientDataEventFieldInterface {
	return &NullableAdobeCommerceEventsClientDataEventFieldInterface{value: val, isSet: true}
}

func (v NullableAdobeCommerceEventsClientDataEventFieldInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdobeCommerceEventsClientDataEventFieldInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
