/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the PostV1ReturnsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostV1ReturnsRequest{}

// PostV1ReturnsRequest struct for PostV1ReturnsRequest
type PostV1ReturnsRequest struct {
	RmaDataObject        RmaDataRmaInterface `json:"rmaDataObject"`
	AdditionalProperties map[string]interface{}
}

type _PostV1ReturnsRequest PostV1ReturnsRequest

// NewPostV1ReturnsRequest instantiates a new PostV1ReturnsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostV1ReturnsRequest(rmaDataObject RmaDataRmaInterface) *PostV1ReturnsRequest {
	this := PostV1ReturnsRequest{}
	this.RmaDataObject = rmaDataObject
	return &this
}

// NewPostV1ReturnsRequestWithDefaults instantiates a new PostV1ReturnsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostV1ReturnsRequestWithDefaults() *PostV1ReturnsRequest {
	this := PostV1ReturnsRequest{}
	return &this
}

// GetRmaDataObject returns the RmaDataObject field value
func (o *PostV1ReturnsRequest) GetRmaDataObject() RmaDataRmaInterface {
	if o == nil {
		var ret RmaDataRmaInterface
		return ret
	}

	return o.RmaDataObject
}

// GetRmaDataObjectOk returns a tuple with the RmaDataObject field value
// and a boolean to check if the value has been set.
func (o *PostV1ReturnsRequest) GetRmaDataObjectOk() (*RmaDataRmaInterface, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RmaDataObject, true
}

// SetRmaDataObject sets field value
func (o *PostV1ReturnsRequest) SetRmaDataObject(v RmaDataRmaInterface) {
	o.RmaDataObject = v
}

func (o PostV1ReturnsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostV1ReturnsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rmaDataObject"] = o.RmaDataObject

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostV1ReturnsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rmaDataObject",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostV1ReturnsRequest := _PostV1ReturnsRequest{}

	err = json.Unmarshal(data, &varPostV1ReturnsRequest)

	if err != nil {
		return err
	}

	*o = PostV1ReturnsRequest(varPostV1ReturnsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "rmaDataObject")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PostV1ReturnsRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *PostV1ReturnsRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullablePostV1ReturnsRequest struct {
	value *PostV1ReturnsRequest
	isSet bool
}

func (v NullablePostV1ReturnsRequest) Get() *PostV1ReturnsRequest {
	return v.value
}

func (v *NullablePostV1ReturnsRequest) Set(val *PostV1ReturnsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostV1ReturnsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostV1ReturnsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostV1ReturnsRequest(val *PostV1ReturnsRequest) *NullablePostV1ReturnsRequest {
	return &NullablePostV1ReturnsRequest{value: val, isSet: true}
}

func (v NullablePostV1ReturnsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostV1ReturnsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
