/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentServicesPaypalDataPaymentSdkParamsInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentServicesPaypalDataPaymentSdkParamsInterface{}

// PaymentServicesPaypalDataPaymentSdkParamsInterface
type PaymentServicesPaypalDataPaymentSdkParamsInterface struct {
	// The payments sdk code
	Code string `json:"code"`
	// The payments sdk params
	Params               []PaymentServicesPaypalDataPaymentConfigSdkParamsInterface `json:"params"`
	AdditionalProperties map[string]interface{}
}

type _PaymentServicesPaypalDataPaymentSdkParamsInterface PaymentServicesPaypalDataPaymentSdkParamsInterface

// NewPaymentServicesPaypalDataPaymentSdkParamsInterface instantiates a new PaymentServicesPaypalDataPaymentSdkParamsInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentServicesPaypalDataPaymentSdkParamsInterface(code string, params []PaymentServicesPaypalDataPaymentConfigSdkParamsInterface) *PaymentServicesPaypalDataPaymentSdkParamsInterface {
	this := PaymentServicesPaypalDataPaymentSdkParamsInterface{}
	this.Code = code
	this.Params = params
	return &this
}

// NewPaymentServicesPaypalDataPaymentSdkParamsInterfaceWithDefaults instantiates a new PaymentServicesPaypalDataPaymentSdkParamsInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentServicesPaypalDataPaymentSdkParamsInterfaceWithDefaults() *PaymentServicesPaypalDataPaymentSdkParamsInterface {
	this := PaymentServicesPaypalDataPaymentSdkParamsInterface{}
	return &this
}

// GetCode returns the Code field value
func (o *PaymentServicesPaypalDataPaymentSdkParamsInterface) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *PaymentServicesPaypalDataPaymentSdkParamsInterface) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *PaymentServicesPaypalDataPaymentSdkParamsInterface) SetCode(v string) {
	o.Code = v
}

// GetParams returns the Params field value
func (o *PaymentServicesPaypalDataPaymentSdkParamsInterface) GetParams() []PaymentServicesPaypalDataPaymentConfigSdkParamsInterface {
	if o == nil {
		var ret []PaymentServicesPaypalDataPaymentConfigSdkParamsInterface
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *PaymentServicesPaypalDataPaymentSdkParamsInterface) GetParamsOk() ([]PaymentServicesPaypalDataPaymentConfigSdkParamsInterface, bool) {
	if o == nil {
		return nil, false
	}
	return o.Params, true
}

// SetParams sets field value
func (o *PaymentServicesPaypalDataPaymentSdkParamsInterface) SetParams(v []PaymentServicesPaypalDataPaymentConfigSdkParamsInterface) {
	o.Params = v
}

func (o PaymentServicesPaypalDataPaymentSdkParamsInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentServicesPaypalDataPaymentSdkParamsInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["params"] = o.Params

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentServicesPaypalDataPaymentSdkParamsInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"params",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentServicesPaypalDataPaymentSdkParamsInterface := _PaymentServicesPaypalDataPaymentSdkParamsInterface{}

	err = json.Unmarshal(data, &varPaymentServicesPaypalDataPaymentSdkParamsInterface)

	if err != nil {
		return err
	}

	*o = PaymentServicesPaypalDataPaymentSdkParamsInterface(varPaymentServicesPaypalDataPaymentSdkParamsInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "params")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *PaymentServicesPaypalDataPaymentSdkParamsInterface) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *PaymentServicesPaypalDataPaymentSdkParamsInterface) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullablePaymentServicesPaypalDataPaymentSdkParamsInterface struct {
	value *PaymentServicesPaypalDataPaymentSdkParamsInterface
	isSet bool
}

func (v NullablePaymentServicesPaypalDataPaymentSdkParamsInterface) Get() *PaymentServicesPaypalDataPaymentSdkParamsInterface {
	return v.value
}

func (v *NullablePaymentServicesPaypalDataPaymentSdkParamsInterface) Set(val *PaymentServicesPaypalDataPaymentSdkParamsInterface) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentServicesPaypalDataPaymentSdkParamsInterface) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentServicesPaypalDataPaymentSdkParamsInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentServicesPaypalDataPaymentSdkParamsInterface(val *PaymentServicesPaypalDataPaymentSdkParamsInterface) *NullablePaymentServicesPaypalDataPaymentSdkParamsInterface {
	return &NullablePaymentServicesPaypalDataPaymentSdkParamsInterface{value: val, isSet: true}
}

func (v NullablePaymentServicesPaypalDataPaymentSdkParamsInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentServicesPaypalDataPaymentSdkParamsInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
