/*
Commerce Admin REST endpoints - All inclusive

The schemas documented here are autogenerated from an instance of Adobe Commerce with B2B. Each schema represents a specific user role (Admin, Customer, and Guest) and determines which endpoints are accessible. Use the version switcher to select an Adobe Commerce version and corresponding API.  You can also <a href=\"https://developer.adobe.com/commerce/webapi/rest/quick-reference/generate-local\" target=\"_blank\">generate a local API reference</a> based on your own Adobe Commerce configuration, which allows you to see API documentation for your specific Adobe Commerce modules, third-party modules, and extension attributes.

API version: 2.4.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package magento

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigurableProductDataConfigurableItemOptionValueInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurableProductDataConfigurableItemOptionValueInterface{}

// ConfigurableProductDataConfigurableItemOptionValueInterface Interface ConfigurableItemOptionValueInterface
type ConfigurableProductDataConfigurableItemOptionValueInterface struct {
	// Option SKU
	OptionId string `json:"option_id"`
	// Item id
	OptionValue *int32 `json:"option_value,omitempty"`
	// ExtensionInterface class for @see \\Magento\\ConfigurableProduct\\Api\\Data\\ConfigurableItemOptionValueInterface
	ExtensionAttributes  map[string]interface{} `json:"extension_attributes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConfigurableProductDataConfigurableItemOptionValueInterface ConfigurableProductDataConfigurableItemOptionValueInterface

// NewConfigurableProductDataConfigurableItemOptionValueInterface instantiates a new ConfigurableProductDataConfigurableItemOptionValueInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurableProductDataConfigurableItemOptionValueInterface(optionId string) *ConfigurableProductDataConfigurableItemOptionValueInterface {
	this := ConfigurableProductDataConfigurableItemOptionValueInterface{}
	this.OptionId = optionId
	return &this
}

// NewConfigurableProductDataConfigurableItemOptionValueInterfaceWithDefaults instantiates a new ConfigurableProductDataConfigurableItemOptionValueInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurableProductDataConfigurableItemOptionValueInterfaceWithDefaults() *ConfigurableProductDataConfigurableItemOptionValueInterface {
	this := ConfigurableProductDataConfigurableItemOptionValueInterface{}
	return &this
}

// GetOptionId returns the OptionId field value
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) GetOptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OptionId
}

// GetOptionIdOk returns a tuple with the OptionId field value
// and a boolean to check if the value has been set.
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) GetOptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OptionId, true
}

// SetOptionId sets field value
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) SetOptionId(v string) {
	o.OptionId = v
}

// GetOptionValue returns the OptionValue field value if set, zero value otherwise.
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) GetOptionValue() int32 {
	if o == nil || IsNil(o.OptionValue) {
		var ret int32
		return ret
	}
	return *o.OptionValue
}

// GetOptionValueOk returns a tuple with the OptionValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) GetOptionValueOk() (*int32, bool) {
	if o == nil || IsNil(o.OptionValue) {
		return nil, false
	}
	return o.OptionValue, true
}

// HasOptionValue returns a boolean if a field has been set.
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) HasOptionValue() bool {
	if o != nil && !IsNil(o.OptionValue) {
		return true
	}

	return false
}

// SetOptionValue gets a reference to the given int32 and assigns it to the OptionValue field.
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) SetOptionValue(v int32) {
	o.OptionValue = &v
}

// GetExtensionAttributes returns the ExtensionAttributes field value if set, zero value otherwise.
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) GetExtensionAttributes() map[string]interface{} {
	if o == nil || IsNil(o.ExtensionAttributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.ExtensionAttributes
}

// GetExtensionAttributesOk returns a tuple with the ExtensionAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) GetExtensionAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExtensionAttributes) {
		return map[string]interface{}{}, false
	}
	return o.ExtensionAttributes, true
}

// HasExtensionAttributes returns a boolean if a field has been set.
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) HasExtensionAttributes() bool {
	if o != nil && !IsNil(o.ExtensionAttributes) {
		return true
	}

	return false
}

// SetExtensionAttributes gets a reference to the given map[string]interface{} and assigns it to the ExtensionAttributes field.
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) SetExtensionAttributes(v map[string]interface{}) {
	o.ExtensionAttributes = v
}

func (o ConfigurableProductDataConfigurableItemOptionValueInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurableProductDataConfigurableItemOptionValueInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["option_id"] = o.OptionId
	if !IsNil(o.OptionValue) {
		toSerialize["option_value"] = o.OptionValue
	}
	if !IsNil(o.ExtensionAttributes) {
		toSerialize["extension_attributes"] = o.ExtensionAttributes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"option_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigurableProductDataConfigurableItemOptionValueInterface := _ConfigurableProductDataConfigurableItemOptionValueInterface{}

	err = json.Unmarshal(data, &varConfigurableProductDataConfigurableItemOptionValueInterface)

	if err != nil {
		return err
	}

	*o = ConfigurableProductDataConfigurableItemOptionValueInterface(varConfigurableProductDataConfigurableItemOptionValueInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "option_id")
		delete(additionalProperties, "option_value")
		delete(additionalProperties, "extension_attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *ConfigurableProductDataConfigurableItemOptionValueInterface) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableConfigurableProductDataConfigurableItemOptionValueInterface struct {
	value *ConfigurableProductDataConfigurableItemOptionValueInterface
	isSet bool
}

func (v NullableConfigurableProductDataConfigurableItemOptionValueInterface) Get() *ConfigurableProductDataConfigurableItemOptionValueInterface {
	return v.value
}

func (v *NullableConfigurableProductDataConfigurableItemOptionValueInterface) Set(val *ConfigurableProductDataConfigurableItemOptionValueInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurableProductDataConfigurableItemOptionValueInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurableProductDataConfigurableItemOptionValueInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurableProductDataConfigurableItemOptionValueInterface(val *ConfigurableProductDataConfigurableItemOptionValueInterface) *NullableConfigurableProductDataConfigurableItemOptionValueInterface {
	return &NullableConfigurableProductDataConfigurableItemOptionValueInterface{value: val, isSet: true}
}

func (v NullableConfigurableProductDataConfigurableItemOptionValueInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurableProductDataConfigurableItemOptionValueInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
